import type {
  BoxDefinition,
  DungeonDefinition,
  GearDefinition,
  HeroDefinition,
  Rarity,
  RunBuff,
} from "./types";

export const RARITY_ORDER: Rarity[] = [
  "Common",
  "Uncommon",
  "Rare",
  "Epic",
  "Legendary",
  "Mythic",
  "Secret",
];

export const HEROES: HeroDefinition[] = [
  {
    id: "astra",
    name: "Astra",
    epithet: "Sonnenpfeil",
    role: "Fernkampf-DPS",
    rarity: "Rare",
    baseHp: 118,
    baseAttack: 34,
    baseDefense: 4,
    speed: 112,
    activeName: "Sternenregen",
    activeDescription: "Trifft alle Gegner und markiert das schwächste Ziel.",
    passiveName: "Ruhige Hand",
    passiveDescription: "Jeder fünfte Treffer ist garantiert kritisch.",
    palette: "#f0b84f",
    portrait: "archer",
  },
  {
    id: "brann",
    name: "Brann",
    epithet: "Moosschild",
    role: "Tank",
    rarity: "Uncommon",
    baseHp: 198,
    baseAttack: 18,
    baseDefense: 12,
    speed: 82,
    activeName: "Eichenwall",
    activeDescription: "Verleiht dem Team Schilde und zieht Gegner an.",
    passiveName: "Standfest",
    passiveDescription: "Erleidet in der Front 18 % weniger Schaden.",
    palette: "#6cc589",
    portrait: "guardian",
  },
  {
    id: "mira",
    name: "Mira",
    epithet: "Waldlicht",
    role: "Heiler",
    rarity: "Uncommon",
    baseHp: 136,
    baseAttack: 14,
    baseDefense: 6,
    speed: 96,
    activeName: "Blütensegen",
    activeDescription: "Heilt das gesamte Team und entfernt Verwundung.",
    passiveName: "Sanfte Rast",
    passiveDescription: "Helden regenerieren im Schutzraum 50 % schneller.",
    palette: "#63d6b2",
    portrait: "healer",
  },
  {
    id: "kael",
    name: "Kael",
    epithet: "Klingenwirbel",
    role: "Nahkampf-DPS",
    rarity: "Common",
    baseHp: 148,
    baseAttack: 29,
    baseDefense: 7,
    speed: 103,
    activeName: "Wirbelhieb",
    activeDescription: "Drei schnelle Hiebe gegen das aktuelle Ziel.",
    passiveName: "Kampfeslust",
    passiveDescription: "Unter 40 % Leben steigt sein Angriff.",
    palette: "#ef765f",
    portrait: "knight",
  },
  {
    id: "fenn",
    name: "Fenn",
    epithet: "Glückssänger",
    role: "Support",
    rarity: "Epic",
    baseHp: 142,
    baseAttack: 19,
    baseDefense: 7,
    speed: 118,
    activeName: "Mutige Melodie",
    activeDescription: "Beschleunigt alle Helden und gibt einen kleinen Schild.",
    passiveName: "Zweite Strophe",
    passiveDescription: "Jeder dritte Buff hält zwei Sekunden länger.",
    palette: "#b78bef",
    portrait: "bard",
  },
  {
    id: "nyra",
    name: "Nyra",
    epithet: "Nebeltritt",
    role: "Nahkampf-DPS",
    rarity: "Rare",
    baseHp: 126,
    baseAttack: 38,
    baseDefense: 4,
    speed: 128,
    activeName: "Schattensprung",
    activeDescription: "Springt zum schwächsten Gegner und verursacht hohen Schaden.",
    passiveName: "Ausweichen",
    passiveDescription: "Kann langsamen Angriffen vollständig entgehen.",
    palette: "#7795ed",
    portrait: "rogue",
  },
  {
    id: "solenne",
    name: "Solenne",
    epithet: "Morgenstern",
    role: "Support",
    rarity: "Legendary",
    baseHp: 164,
    baseAttack: 28,
    baseDefense: 9,
    speed: 108,
    activeName: "Goldene Stunde",
    activeDescription: "Heilt, stärkt und schützt das Team gleichzeitig.",
    passiveName: "Erster Sonnenstrahl",
    passiveDescription: "Das Team beginnt jeden Kampf mit 20 Energie.",
    palette: "#f2c65f",
    portrait: "mage",
  },
  {
    id: "vesper",
    name: "Vesper",
    epithet: "Zwischen den Welten",
    role: "Fernkampf-DPS",
    rarity: "Secret",
    baseHp: 150,
    baseAttack: 46,
    baseDefense: 8,
    speed: 122,
    activeName: "Riss im Himmel",
    activeDescription: "Verdoppelt den nächsten Schaden aller Helden.",
    passiveName: "Unmögliches Glück",
    passiveDescription: "Seltene Effekte können ein zweites Mal ausgelöst werden.",
    palette: "#ff6ab8",
    portrait: "mage",
  },
];

export const GEAR: GearDefinition[] = [
  {
    id: "oakblade",
    name: "Eichenklinge",
    slot: "Waffe",
    rarity: "Uncommon",
    attack: 8,
    perk: "Der erste Treffer erhält +20 % Schaden.",
    icon: "blade",
  },
  {
    id: "sunbow",
    name: "Sonnenbogen",
    slot: "Waffe",
    rarity: "Rare",
    attack: 13,
    speed: 4,
    perk: "Kritische Treffer laden 5 Energie.",
    icon: "bow",
  },
  {
    id: "mossmail",
    name: "Moospanzer",
    slot: "Rüstung",
    rarity: "Uncommon",
    hp: 28,
    defense: 5,
    perk: "Im Schutzraum +5 % Regeneration.",
    icon: "armor",
  },
  {
    id: "wardenplate",
    name: "Wächterplatte",
    slot: "Rüstung",
    rarity: "Epic",
    hp: 45,
    defense: 9,
    perk: "Beim Eintritt 25 Schild erhalten.",
    icon: "armor",
  },
  {
    id: "dew-ring",
    name: "Tauring",
    slot: "Ring",
    rarity: "Rare",
    hp: 18,
    speed: 7,
    perk: "Heilungen wirken 12 % stärker.",
    icon: "ring",
  },
  {
    id: "fox-charm",
    name: "Fuchstalisman",
    slot: "Relikt",
    rarity: "Epic",
    attack: 9,
    speed: 10,
    perk: "Der erste Ausweichversuch gelingt.",
    icon: "relic",
  },
  {
    id: "ember-crown",
    name: "Glutkrone",
    slot: "Relikt",
    rarity: "Legendary",
    attack: 18,
    hp: 30,
    perk: "Fähigkeiten verursachen Flächenschaden.",
    icon: "crown",
  },
];

export const COSMETICS = [
  { id: "trail-fireflies", name: "Glühwürmchen-Spur", rarity: "Rare" as Rarity },
  { id: "title-pathfinder", name: "Titel: Pfadfinder", rarity: "Uncommon" as Rarity },
  { id: "emote-campfire", name: "Emote: Lagerfeuer", rarity: "Common" as Rarity },
  { id: "skin-moonlit", name: "Skin: Mondlicht", rarity: "Epic" as Rarity },
  { id: "aura-secret-grove", name: "Aura: Geheimer Hain", rarity: "Secret" as Rarity },
];

export const BOXES: BoxDefinition[] = [
  {
    id: "hero-box",
    name: "Heldenbox",
    subtitle: "Neue Gefährten für dein Abenteuer",
    kind: "hero",
    cost: 1,
    currency: "keys",
    pityMax: 20,
    accent: "#6e9fe9",
    availability: "Immer verfügbar",
    chances: { Common: 42, Uncommon: 30, Rare: 17, Epic: 8, Legendary: 2.5, Secret: 0.5 },
    contents: HEROES.map((hero) => hero.id),
  },
  {
    id: "gear-box",
    name: "Ausrüstungsbox",
    subtitle: "Waffen, Rüstungen, Ringe und Relikte",
    kind: "gear",
    cost: 300,
    currency: "gold",
    pityMax: 15,
    accent: "#e5ae52",
    availability: "Immer verfügbar",
    chances: { Common: 30, Uncommon: 35, Rare: 22, Epic: 10, Legendary: 3 },
    contents: GEAR.map((gear) => gear.id),
  },
  {
    id: "cosmetic-box",
    name: "Kosmetikbox",
    subtitle: "Nur Stil, niemals Stärke",
    kind: "cosmetic",
    cost: 25,
    currency: "crystals",
    pityMax: 12,
    accent: "#b78bef",
    availability: "Immer verfügbar",
    chances: { Common: 35, Uncommon: 30, Rare: 22, Epic: 11, Secret: 2 },
    contents: COSMETICS.map((cosmetic) => cosmetic.id),
  },
  {
    id: "event-box",
    name: "Blütenfest-Box",
    subtitle: "Zeitlich passende Heldenstile und Effekte",
    kind: "event",
    cost: 40,
    currency: "crystals",
    pityMax: 10,
    accent: "#ef7ca7",
    availability: "Blütenfest · 12 Tage",
    chances: { Uncommon: 35, Rare: 35, Epic: 22, Legendary: 7, Secret: 1 },
    contents: ["trail-fireflies", "skin-moonlit", "aura-secret-grove"],
  },
  {
    id: "boss-box",
    name: "Bossbox",
    subtitle: "Nur durch besiegte Bosse verdient",
    kind: "boss",
    cost: 1,
    currency: "bossKeys",
    pityMax: 5,
    accent: "#e76577",
    availability: "Waldhüter Nox besiegen",
    chances: { Rare: 48, Epic: 35, Legendary: 14, Mythic: 2.5, Secret: 0.5 },
    contents: ["wardenplate", "fox-charm", "ember-crown", "solenne", "vesper"],
  },
];

export const DUNGEONS: DungeonDefinition[] = [
  {
    id: "whispering-woods",
    name: "Flüsterwald",
    subtitle: "Kapitel I",
    description: "Ein freundlicher Wald ist aus dem Takt geraten. Folge den Irrlichtern bis zu Nox.",
    theme: "forest",
    difficulty: 1,
    recommendedPower: 320,
    boss: "Waldhüter Nox",
    mechanic: "Heilpflanzen · Hinterhalte · verborgene Pfade",
    accent: "#58b986",
  },
  {
    id: "frostglass-cavern",
    name: "Frostglas-Höhlen",
    subtitle: "Kapitel II",
    description: "Gefrorene Hallen, in denen jeder Schritt über das Eis entscheidet.",
    theme: "frost",
    difficulty: 2,
    recommendedPower: 620,
    boss: "Königin Skadi",
    mechanic: "Verlangsamung · Einfrieren · rutschige Felder",
    accent: "#65aee8",
  },
  {
    id: "emberpeak",
    name: "Glutgipfel",
    subtitle: "Kapitel III",
    description: "Lavaadern durchziehen die Festung eines uralten Feuerriesen.",
    theme: "ember",
    difficulty: 3,
    recommendedPower: 980,
    boss: "Vulkanherz Arkon",
    mechanic: "Lavafelder · Umgebungsschaden · Feuergegner",
    accent: "#eb7857",
  },
  {
    id: "velvet-void",
    name: "Samtene Leere",
    subtitle: "Kapitel IV",
    description: "Der Dungeon verändert sich, sobald du glaubst, ihn verstanden zu haben.",
    theme: "void",
    difficulty: 4,
    recommendedPower: 1420,
    boss: "Die Namenlose Form",
    mechanic: "Veränderte Räume · riskante Buffs · hohe Beute",
    accent: "#a57ae6",
  },
];

export const RUN_BUFFS: RunBuff[] = [
  { id: "thorn-strikes", name: "Dornenfolge", icon: "burst", description: "Jeder fünfte Treffer verursacht Flächenschaden." },
  { id: "sanctuary-bloom", name: "Blühender Schutz", icon: "leaf", description: "Der Schutzraum heilt 70 % schneller." },
  { id: "guardian-return", name: "Mutige Rückkehr", icon: "shield", description: "Helden erhalten beim Verlassen des Schutzraums 35 Schild." },
  { id: "healing-rain", name: "Heilender Regen", icon: "drop", description: "Heilungen treffen zusätzlich den schwächsten Helden." },
  { id: "double-arrow", name: "Zwillingspfeil", icon: "arrow", description: "Fernkämpfer treffen ein zweites Ziel." },
  { id: "slow-crit", name: "Frostkrit", icon: "snow", description: "Kritische Treffer verzögern den nächsten Gegnerangriff." },
  { id: "wild-force", name: "Wilde Kraft", icon: "claw", description: "+20 % Angriff, aber 8 % weniger Rüstung." },
  { id: "last-light", name: "Letztes Licht", icon: "sun", description: "Einmal pro Kampf bleibt ein Held mit 1 Leben stehen." },
  { id: "shared-aegis", name: "Geteilter Schild", icon: "ward", description: "Überschüssige Heilung wird zu Schild." },
  { id: "warm-core", name: "Warmer Kern", icon: "sun", description: "Frostwellen verzögern Helden nur halb so lange." },
  { id: "crystal-guard", name: "Kristallwacht", icon: "shield", description: "Nach jeder Frostwelle erhält das aktive Team 16 Schild." },
  { id: "shatterpoint", name: "Bruchstelle", icon: "burst", description: "In den Frostglas-Höhlen verursacht das Team 15 % mehr Schaden." },
  { id: "shelter-thaw", name: "Taukammer", icon: "snow", description: "Der Held im Schutzraum lädt während einer Frostwelle 25 Energie." },
];

export const CURRENCY_LABELS = {
  gold: "Gold",
  keys: "Schlüssel",
  crystals: "Kristalle",
  bossKeys: "Boss-Siegel",
} as const;

export function getHero(id: string) {
  return HEROES.find((hero) => hero.id === id);
}

export function getGear(id: string) {
  return GEAR.find((gear) => gear.id === id);
}

export function getBox(id: string) {
  return BOXES.find((box) => box.id === id);
}

export function getDungeon(id: string) {
  return DUNGEONS.find((dungeon) => dungeon.id === id);
}
